// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1SXadmSTfFHnPvAGPfexs1mimuci6JY',
    appId: '1:509508250990:web:4b1da39125540fa2a1257f',
    messagingSenderId: '509508250990',
    projectId: 'chat-app-e3da8',
    authDomain: 'chat-app-e3da8.firebaseapp.com',
    storageBucket: 'chat-app-e3da8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFx4QbIto3vFbrQZOOhosUOYpCJBjYqQo',
    appId: '1:509508250990:android:9b78256964272572a1257f',
    messagingSenderId: '509508250990',
    projectId: 'chat-app-e3da8',
    storageBucket: 'chat-app-e3da8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfAepRRsmqc2CmlEWBrSwOkGk2LHg5i_0',
    appId: '1:509508250990:ios:ab991bfcd8a07b7ba1257f',
    messagingSenderId: '509508250990',
    projectId: 'chat-app-e3da8',
    storageBucket: 'chat-app-e3da8.firebasestorage.app',
    iosBundleId: 'com.example.fullstackCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfAepRRsmqc2CmlEWBrSwOkGk2LHg5i_0',
    appId: '1:509508250990:ios:ab991bfcd8a07b7ba1257f',
    messagingSenderId: '509508250990',
    projectId: 'chat-app-e3da8',
    storageBucket: 'chat-app-e3da8.firebasestorage.app',
    iosBundleId: 'com.example.fullstackCallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1SXadmSTfFHnPvAGPfexs1mimuci6JY',
    appId: '1:509508250990:web:e6d79790dcd0d9fba1257f',
    messagingSenderId: '509508250990',
    projectId: 'chat-app-e3da8',
    authDomain: 'chat-app-e3da8.firebaseapp.com',
    storageBucket: 'chat-app-e3da8.firebasestorage.app',
  );

}